spring:
  application:
    name: orderclient
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pm110?serverTimezone=GMT%2B8&characterEncoding=UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

env: "envasdasdsa"

server:
  port: 8089
