spring:
  application:
    name: productclient
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/pm110?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8088
  
env: env1

